# 端口
server:
  port: 8080

spring:
  application:
    name: happy-uaa
  datasource:
    url: jdbc:mysql://localhost:3306/happy_admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

happy:
  code:
    swagger:
      group: ${spring.application.name}
      base-package: cool.happycoding.uaa
      title: happy-uaa
      description: happy-uaa
      version: 1.0
      contact:
        name: happycoding
        email: happycoding@aliyun.com
      enable: true
